import assert from 'node:assert/strict';
import {calculateBusinessCase,example} from './gsa-economia.mjs';
const close=(actual,expected)=>assert.ok(Math.abs(actual-expected)<1e-7,`${actual} != ${expected}`);
const original=structuredClone(example);original.operations=original.operations.filter(r=>r.kind==='permanece');
let r=calculateBusinessCase(original);close(r.totalHours,600);close(r.totalFte,600/132);
close(r.groups[0].hoursSaved,320);close(r.groups[1].hoursSaved,140);close(r.groups[2].hoursSaved,60);close(r.groups[3].hoursSaved,80);
close(r.months[2].op,0);close(r.months[3].op,r.operation/6);close(r.months[8].op,r.operation);
close(r.months[5].techSaving,0);close(r.months[6].techSaving,60000);close(r.months[0].techCost,35000);
const zero=structuredClone(example);zero.operations.forEach(row=>row.conversion=0);zero.technology=[];zero.others=[];
r=calculateBusinessCase(zero);close(r.operation,0);close(r.net60,0);close(r.roi,-1);assert.equal(r.payback,null);assert.ok(r.totalFte>0);
const recovery=structuredClone(example);recovery.operations=[];recovery.others=[];recovery.settings.capex=1000;recovery.settings.upfront=200;recovery.settings.discount=0;
recovery.technology=[{kind:'saving',amount:100,start:1}];r=calculateBusinessCase(recovery);
close(r.net60,6000);close(r.netReturn,4800);close(r.roi,4);close(r.npv,4800);assert.equal(r.payback,12);close(r.years[0].net,1200);
recovery.settings.capex=0;recovery.settings.upfront=0;r=calculateBusinessCase(recovery);assert.equal(r.roi,null);assert.equal(r.payback,null);
const residual=structuredClone(original);residual.operations=[{group:'analistas',kind:'elimina',volume:100,before:6,after:2,coverage:50,conversion:100}];
r=calculateBusinessCase(residual);close(r.totalHours,100*.5*4/60);close(r.groups[0].baselineHours,10);close(r.groups[0].afterHours,10-100*.5*4/60);
residual.operations[0].after=8;residual.operations[0].conversion=0;r=calculateBusinessCase(residual);assert.ok(r.operation<0);
const discounted=structuredClone(recovery);discounted.settings.capex=1200;discounted.settings.discount=10;r=calculateBusinessCase(discounted);assert.ok(r.npv<r.netReturn);
const totals=calculateBusinessCase(example);close(totals.years.reduce((s,y)=>s+y.net,0),totals.net60);close(totals.months.at(-1).cumulative,totals.netReturn);
console.log('11 cenários validados: FTE, eliminação residual, conversão, rampa, custos, ROI, payback, VPL e acumulados.');
console.log(JSON.stringify({hours:totals.totalHours,fte:totals.totalFte,month12:totals.months[11].net,year1:totals.years[0].net,fiveYears:totals.net60,netReturn:totals.netReturn,roi:totals.roi,payback:totals.payback,npv:totals.npv}));
