export type Case = {id:string;name:string;vehicle:string;workshop:string;type:string;stage:number;action:string;reason:string;sla:string;risk:'Crítico'|'Atenção'|'No prazo';complexity:number;done:boolean;validated:boolean;points:number;note:string;priorityEarned?:boolean;slaEarned?:boolean};
export const seed:Case[] = [
{id:'000238172',name:'Mariana Oliveira',vehicle:'Volkswagen T-Cross · 2024',workshop:'Auto Center Paulista',type:'Colisão',stage:2,action:'Analisar orçamento',reason:'Vistoria concluída há 22h. Oficina aguarda autorização para iniciar o reparo.',sla:'2h14',risk:'Crítico',complexity:1.5,done:false,validated:false,points:0,note:''},
{id:'000239541',name:'Rafael Almeida',vehicle:'Chevrolet Onix · 2023',workshop:'Oficina Nova Lapa',type:'Colisão',stage:1,action:'Validar documentos',reason:'Documentação retornada. Validação libera a etapa de vistoria.',sla:'3h40',risk:'Atenção',complexity:1,done:false,validated:false,points:0,note:''},
{id:'000240013',name:'Camila Santos',vehicle:'Hyundai HB20 · 2022',workshop:'Centro Automotivo Sul',type:'Colisão',stage:3,action:'Tratar peça pendente',reason:'Peça sem previsão há 5 dias. Confirmar disponibilidade e alternativa de fornecimento.',sla:'1h05',risk:'Crítico',complexity:1.5,done:false,validated:false,points:0,note:''},
{id:'000237784',name:'Lucas Ferreira',vehicle:'Fiat Argo · 2024',workshop:'Oficina Pinheiros',type:'Dano material',stage:1,action:'Retornar cliente',reason:'Cliente aguarda atualização sobre documentos e próximos passos.',sla:'5h20',risk:'Atenção',complexity:1,done:false,validated:false,points:0,note:''},
{id:'000240228',name:'Juliana Costa',vehicle:'Toyota Corolla · 2023',workshop:'Auto Center Norte',type:'Colisão',stage:2,action:'Autorizar reparo',reason:'Orçamento aprovado. Autorizar oficina para avançar o veículo ao reparo.',sla:'7h10',risk:'No prazo',complexity:1,done:false,validated:false,points:0,note:''},
{id:'000240315',name:'Bruno Lima',vehicle:'Jeep Renegade · 2022',workshop:'Oficina Mooca',type:'Dano material',stage:4,action:'Confirmar entrega',reason:'Reparo concluído. Confirmar entrega e orientar o segurado.',sla:'8h30',risk:'No prazo',complexity:1,done:false,validated:false,points:0,note:''}
];
export const stages=['Aviso','Documentação','Análise','Reparo','Entrega','Encerrado'];
export function score(c:Case,priority:boolean,onTime:boolean){return ( (priority?10:0)+(onTime?5:0) )*c.complexity;}
