import {useState} from 'react';
import {Search,House,BriefcaseBusiness,ChartNoAxesCombined,Clock,ShieldCheck,Check,ChevronRight,RotateCcw,X,FileText} from 'lucide-react';
import {seed,stages,type Case} from './data';
import Epic from './Epic';

const key='gsa-operacao-v1';
function initial():Case[]{try{const stored=JSON.parse(localStorage.getItem(key)||'null');if(Array.isArray(stored)&&stored.length===seed.length&&stored.every(c=>seed.some(s=>s.id===c.id)&&typeof c.done==='boolean'))return stored;}catch{}return seed;}
export default function Operational(){
 const [cases,setCases]=useState(initial),[page,setPage]=useState(new URLSearchParams(location.search).get('aba')==='escopo'?'escopo':'inicio'),[selected,setSelected]=useState<string|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('Todos'),[period,setPeriod]=useState('Esta semana'),[note,setNote]=useState(''),[modal,setModal]=useState(false),[reset,setReset]=useState(false),[onTime,setOnTime]=useState(true),[notice,setNotice]=useState('');
 const queue=cases.filter(c=>!c.done).sort((a,b)=>({'Crítico':0,'Atenção':1,'No prazo':2}[a.risk]-{'Crítico':0,'Atenção':1,'No prazo':2}[b.risk]));
 const current=cases.find(c=>c.id===selected),completed=cases.filter(c=>c.done).length,pending=cases.filter(c=>c.done&&!c.validated);
 function save(next:Case[]){setCases(next);try{localStorage.setItem(key,JSON.stringify(next));}catch{}}
 function go(next:string){setPage(next);history.replaceState(null,'',location.pathname+'?versao=operacional&aba='+next);setSelected(null);setQuery('');window.scrollTo(0,0);}
 function open(c:Case){setSelected(c.id);window.scrollTo(0,0);}
 function complete(){if(!current||current.done||!note.trim())return;save(cases.map(c=>c.id===current.id?{...c,done:true,stage:Math.min(5,c.stage+1),note:note.trim(),slaEarned:onTime,points:0}:c));setModal(false);setNotice('Ação registrada. O sinistro avançou para a próxima etapa.');}
 function validate(c:Case){save(cases.map(x=>x.id===c.id?{...x,validated:true}:x));setNotice('Revisão de qualidade registrada.');}
 function pill(c:Case){return <span className={`pill ${c.done?'green':c.risk==='Crítico'?'red':c.risk==='Atenção'?'amber':'blue'}`}>{c.done?'Ação concluída':c.risk}</span>;}
 function card(title:string,children:React.ReactNode,action?:React.ReactNode){return <section className="card"><div className="card-head"><h2>{title}</h2>{action}</div><div className="card-body">{children}</div></section>;}
 function table(items:Case[]){return <div className="table-wrap"><table><thead><tr><th>Sinistro / segurado</th><th>Próxima ação</th><th>SLA restante</th><th>Situação</th><th>Etapa</th></tr></thead><tbody>{items.map(c=><tr key={c.id}><td><button className="text-link" onClick={()=>open(c)}>{c.id}</button><small>{c.name}</small></td><td>{c.action}</td><td className={!c.done&&c.risk==='Crítico'?'danger':''}>{c.done?'Concluída':c.sla}</td><td>{pill(c)}</td><td>{stages[c.stage]}</td></tr>)}</tbody></table>{!items.length&&<div className="empty"><h3>Nenhum caso nesta seleção</h3><p>Altere a busca ou o filtro.</p></div>}</div>;}
 const nav=[['inicio','Início',House],['carteira','Minha carteira',BriefcaseBusiness],['gestor','Visão do gestor',ChartNoAxesCombined],['escopo','Épico e histórias',FileText]] as const;
 return <><header className="global"><span className="brand">GSA</span><span className="global-title">Sinistro Auto</span><label className="global-search"><Search size={17}/><input aria-label="Buscar sinistro ou segurado" placeholder="Buscar sinistro ou segurado…" value={query} onChange={e=>{setQuery(e.target.value);setPage('carteira');setSelected(null);}}/></label><span className="demo-tag">Ambiente de demonstração</span><span className="avatar">SA</span></header><nav className="navigation" aria-label="Navegação principal"><span className="app-name">GSA Console</span>{nav.map(([id,label,Icon])=><button key={id} className={page===id&&!selected?'active':''} onClick={()=>go(id)}><Icon size={16}/>{label}</button>)}</nav><main>
 <div className="page-heading"><div><div className="breadcrumb">GSA Console <ChevronRight size={12}/> {current?'Sinistros':nav.find(n=>n[0]===page)?.[1]}</div><h1>{current?`Sinistro ${current.id}`:page==='inicio'?'Bom dia, Samuel':page==='carteira'?'Minha carteira':page==='escopo'?'Épico e histórias':'Operação em foco'}</h1><p>{current?`${current.type} · ${current.vehicle}`:page==='inicio'?'Prioridades, pendências e andamento da sua carteira.':page==='carteira'?'Consulte os sinistros e registre a próxima ação.':page==='escopo'?'Escopo, esforço e critérios para implementar a experiência operacional.':'Prazos, qualidade e necessidades de apoio da equipe.'}</p></div><div className="heading-actions"><button className="button" onClick={()=>setReset(true)}><RotateCcw size={15}/>Reiniciar demonstração</button>{current&&!current.done&&<button className="button primary" onClick={()=>{setNote('');setOnTime(true);setModal(true);}}>Concluir próxima ação</button>}{current&&<button className="button" onClick={()=>setSelected(null)}>Voltar</button>}</div></div>
 {notice&&<div className="info-banner" role="status"><Check size={18}/><span className="grow">{notice}</span><button aria-label="Fechar aviso" onClick={()=>setNotice('')}><X size={17}/></button></div>}
 {!current&&page==='inicio'&&<><div className="overview four">{[['Ações pendentes',String(queue.length),'Carteira demonstrativa'],['Casos críticos',String(queue.filter(c=>c.risk==='Crítico').length),'Exigem atenção imediata'],['Ações no SLA','96%','Indicador ilustrativo da semana'],['Qualidade','98%','Indicador ilustrativo da semana']].map(([label,value,hint])=><section className="metric" key={label}><span>{label}</span><b>{value}</b><small>{hint}</small></section>)}</div><div className="workspace"><div className="stack">{card('Minha fila priorizada',table(queue.slice(0,4)),<button className="text-link" onClick={()=>go('carteira')}>Ver carteira</button>)}{card('Pendências por etapa',<div className="distribution">{stages.slice(1,5).map(stage=><div className="rule-row" key={stage}><span>{stage}</span><b>{queue.filter(c=>stages[c.stage]===stage).length} ações</b></div>)}</div>)}</div><aside className="stack">{card('Próximo caso recomendado',queue[0]?<><div className="recommendation"><div className="row"><button className="text-link" onClick={()=>open(queue[0])}>{queue[0].id}</button>{pill(queue[0])}</div><h3>{queue[0].action}</h3><p>{queue[0].reason}</p><div className="sla"><Clock size={16}/><b>{queue[0].sla}</b> de SLA restante</div></div><button className="button primary full" onClick={()=>open(queue[0])}>Trabalhar neste caso</button></>:<div className="empty"><h3>Sem ações pendentes</h3><p>Reinicie a demonstração para explorar novamente.</p></div>)}{card('Resumo do dia',<><div className="rule-row"><span>Ações registradas</span><b>{completed}</b></div><div className="rule-row"><span>Aguardando revisão</span><b>{pending.length}</b></div><div className="rule-row"><span>Ações revisadas</span><b>{cases.filter(c=>c.validated).length}</b></div><p className="muted">Movimentações da carteira nesta demonstração.</p></>)}</aside></div></>}
 {!current&&page==='carteira'&&<>{card('Sinistros',<><div className="toolbar"><label className="search-field"><Search size={16}/><input aria-label="Filtrar carteira" placeholder="Número ou nome do segurado" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Situação <select value={filter} onChange={e=>setFilter(e.target.value)}>{['Todos','Crítico','Atenção','No prazo','Concluídos'].map(x=><option key={x}>{x}</option>)}</select></label><span className="muted">{cases.length} sinistros</span></div>{table([...queue,...cases.filter(c=>c.done)].filter(c=>(filter==='Todos'||(filter==='Concluídos'?c.done:!c.done&&c.risk===filter))&&`${c.id} ${c.name}`.toLowerCase().includes(query.toLowerCase())))}</>)}<div className="info-banner"><Clock size={18}/><span>A fila considera prazo, pendências e impacto na jornada do segurado.</span></div></>}
 {current&&<><div className="stage-path">{stages.map((s,i)=><div className={i<current.stage?'complete':i===current.stage?'current':''} key={s}>{i<current.stage?<Check size={15}/>:i+1} {s}</div>)}</div><div className="workspace"><div className="stack">{card('Resumo do sinistro',<><div className="fields">{[['Segurado',current.name],['Veículo',current.vehicle],['Oficina',current.workshop],['Natureza',current.type],['Etapa',stages[current.stage]],['Responsável','Samuel · Célula Auto']].map(([label,value])=><div key={label}><small>{label}</small><b>{value}</b></div>)}</div><div className="recommendation"><h3>{current.done?'Ação registrada':current.action}</h3><p>{current.done?current.note:current.reason}</p>{current.done&&<span className={`pill ${current.validated?'green':'amber'}`}>{current.validated?'Revisão concluída':'Aguardando revisão'}</span>}</div></>)}{card('Histórico',<div className="timeline">{current.done&&<div><Check size={18}/><div><b>Decisão registrada por Samuel</b><p>{current.note}</p><small>{current.slaEarned?'Dentro do SLA':'Fora do SLA'}</small></div></div>}<div><FileText size={18}/><div><b>Documentação disponível para análise</b><small>Hoje · Histórico demonstrativo</small></div></div></div>)}</div><aside className="stack">{card('Prazo da próxima ação',<><div className="big-number">{current.done?'Concluída':current.sla}</div>{pill(current)}<p>{current.reason}</p></>)}{card('Checklist operacional',<div className="checklist"><p><Check size={16}/> Conferir documentos e evidências.</p><p><Check size={16}/> Registrar a decisão e a próxima etapa.</p><p><Check size={16}/> Atualizar oficina e segurado.</p></div>)}</aside></div></>}
 {!current&&page==='gestor'&&<><div className="toolbar"><label>Período <select value={period} onChange={e=>setPeriod(e.target.value)}><option>Esta semana</option><option>Últimas 4 semanas</option></select></label><span className="pill blue">Célula Sinistro Auto</span><span className="muted">Indicadores ilustrativos para apresentação</span></div><div className="overview four">{[['Lead time do sinistro',period==='Esta semana'?'8,4 dias':'9,1 dias','Meta: até 9 dias'],['Ações dentro do SLA',period==='Esta semana'?'96%':'92%','Meta: pelo menos 95%'],['Retrabalho / reabertura',period==='Esta semana'?'2,1%':'3,2%','Meta: abaixo de 3%'],['Contatos por sinistro',period==='Esta semana'?'1,8':'2,3','Meta: até 2 contatos']].map(([label,value,hint])=><section className="metric" key={label}><span>{label}</span><b>{value}</b><small>{hint}</small></section>)}</div><div className="two-column">{card('Ações aguardando revisão',pending.length?pending.map(c=><div className="validation-row" key={c.id}><div><button className="text-link" onClick={()=>open(c)}>{c.id}</button><p>{c.action}</p><small>{c.note}</small></div><button className="button" onClick={()=>validate(c)}>Validar qualidade</button></div>):<div className="empty"><ShieldCheck/><h3>Sem ações pendentes de revisão</h3><p>As ações registradas na carteira aparecem aqui para revisão.</p></div>)}{card('Distribuição da carteira',<>{(['Crítico','Atenção','No prazo'] as const).map(r=><div className="rule-row" key={r}><span>{r}</span><b>{queue.filter(c=>c.risk===r).length} casos</b></div>)}<p className="muted">{completed} ações registradas nesta demonstração.</p></>)}</div>{card('Acompanhamento da célula',<div className="table-wrap"><table><thead><tr><th>Analista</th><th>Ações no SLA</th><th>Qualidade</th><th>Ações realizadas</th><th>Pendências críticas</th></tr></thead><tbody>{[['Samuel','96%','98%',String(12+completed),String(queue.filter(c=>c.risk==='Crítico').length)],['Ana Martins','97%','99%','15','1'],['Diego Souza','95%','97%','13','2']].map(row=><tr key={row[0]}>{row.map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div>)}</>}
 {!current&&page==='escopo'&&<Epic/>}
 <footer><span>GSA · Operação Sinistro Auto</span><span>Dados fictícios · Experiência demonstrativa inspirada no Salesforce Lightning</span></footer></main>
 {(modal||reset)&&<div className="modal-overlay"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="operational-dialog"><div className="card-head"><h2 id="operational-dialog">{reset?'Reiniciar demonstração':'Concluir próxima ação'}</h2><button aria-label="Fechar" onClick={()=>{setModal(false);setReset(false);}}><X size={18}/></button></div><div className="card-body">{reset?<p>Restaurar o cenário inicial desta versão operacional?</p>:<><h3>{current?.action}</h3><label className="form-label">Decisão / ação realizada<textarea autoFocus rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="Registre a decisão e a orientação para a próxima etapa."/></label><label className="checkbox"><input type="checkbox" checked={onTime} onChange={e=>setOnTime(e.target.checked)}/>Ação realizada dentro do SLA</label><p className="muted">A ação registrada ficará disponível para revisão de qualidade.</p></>}</div><div className="modal-footer"><button className="button" onClick={()=>{setModal(false);setReset(false);}}>Cancelar</button><button className="button primary" disabled={!reset&&!note.trim()} onClick={()=>{if(reset){save(seed);setReset(false);setFilter('Todos');setNotice('Demonstração reiniciada.');go('inicio');}else complete();}}>{reset?'Reiniciar':'Registrar ação'}</button></div></section></div>}</>;
}
